/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows HD
 */
public class frmTictTacToe extends javax.swing.JFrame {

    /**
     * Creates new form frmTictTacToe
     */
    private JFrame frame;
    private String startGame = "X";
    private int xCount = 0;
    private int oCount = 0;

    public frmTictTacToe() {
        initComponents();
        this.setVisible(true);
        this.setSize(1200, 600);
        this.setLocationRelativeTo(null);
        jlblPlayerO.setText("      0");
        jlblPlayerX.setText("      0");
        jButton1.setBackground(Color.ORANGE);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.MAGENTA);
        jButton4.setBackground(Color.WHITE);
        jButton5.setBackground(Color.BLUE);
        jButton6.setBackground(Color.PINK);
        jButton7.setBackground(Color.GREEN);
        jButton8.setBackground(Color.darkGray);
        jButton9.setBackground(Color.cyan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlblPlayerX = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jlblPlayerO = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIC TAC TOE");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Player X:");
        jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jlblPlayerX.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlblPlayerX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPlayerX.setText("jLabel4");
        jPanel7.add(jlblPlayerX, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setText("Player O:");
        jPanel11.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jlblPlayerO.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlblPlayerO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPlayerO.setText("jLabel5");
        jPanel12.add(jlblPlayerO, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel12);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel15);

        jPanel16.setLayout(new java.awt.BorderLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel16.add(jbtnReset, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel16);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel17.add(jbtnExit, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel17);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Cofirm if you want to exit", "Tic Tac Toe",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton1.setForeground(Color.GREEN);
        } else {
            jButton1.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerFirstRow();
        gameWinnerFirstColumn();
        gameWinnerDiagonalLeft();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton2.setForeground(Color.GREEN);
        } else {
            jButton2.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerFirstRow();
        gameWinnerSecondColumn();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton3.setForeground(Color.GREEN);
        } else {
            jButton3.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerFirstRow();
        gameWinnerThirdColumn();
        gameWinnerDiagonalRight();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jButton4.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton4.setForeground(Color.GREEN);
        } else {
            jButton4.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerSecondRow();
        gameWinnerFirstColumn();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton5.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton5.setForeground(Color.GREEN);
        } else {
            jButton5.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerSecondRow();
        gameWinnerSecondColumn();
        gameWinnerDiagonalLeft();
        gameWinnerDiagonalRight();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton6.setForeground(Color.GREEN);
        } else {
            jButton6.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerSecondRow();
        gameWinnerThirdColumn();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton7.setForeground(Color.GREEN);
        } else {
            jButton7.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerThirdRow();
        gameWinnerFirstColumn();
        gameWinnerDiagonalRight();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jButton8.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton8.setForeground(Color.GREEN);
        } else {
            jButton8.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerThirdRow();
        gameWinnerSecondColumn();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jlblPlayerX.setText("      0");
        jlblPlayerO.setText("      0");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jButton9.setText(startGame);
        if (startGame.equalsIgnoreCase("X")) {
            jButton9.setForeground(Color.GREEN);
        } else {
            jButton9.setForeground(Color.BLUE);
        }
        choosePlayer();
        gameWinnerThirdRow();
        gameWinnerThirdColumn();
        gameWinnerDiagonalLeft();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTictTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTictTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTictTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTictTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTictTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JLabel jlblPlayerO;
    private javax.swing.JLabel jlblPlayerX;
    // End of variables declaration//GEN-END:variables

    private void gameScore() {
        jlblPlayerX.setText("      " + String.valueOf(xCount));
        jlblPlayerO.setText("      " + String.valueOf(oCount));
    }

    private void choosePlayer() {
        if (startGame.equalsIgnoreCase("X")) {
            startGame = "O";
        } else {
            startGame = "X";
        }
    }

    public void gameWinnerFirstRow() {
        String s1 = jButton1.getText();
        String s2 = jButton2.getText();
        String s3 = jButton3.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }

    public void gameWinnerSecondRow() {
        String s1 = jButton4.getText();
        String s2 = jButton5.getText();
        String s3 = jButton6.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }

    public void gameWinnerThirdRow() {
        String s1 = jButton7.getText();
        String s2 = jButton8.getText();
        String s3 = jButton9.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }

    public void gameWinnerFirstColumn() {
        String s1 = jButton1.getText();
        String s2 = jButton4.getText();
        String s3 = jButton7.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }

    public void gameWinnerSecondColumn() {
        String s1 = jButton2.getText();
        String s2 = jButton5.getText();
        String s3 = jButton8.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }

    public void gameWinnerThirdColumn() {
        String s1 = jButton3.getText();
        String s2 = jButton6.getText();
        String s3 = jButton9.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }

    public void gameWinnerDiagonalLeft() {
        String s1 = jButton1.getText();
        String s2 = jButton5.getText();
        String s3 = jButton9.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }

    public void gameWinnerDiagonalRight() {
        String s1 = jButton3.getText();
        String s2 = jButton5.getText();
        String s3 = jButton7.getText();

        if ((s1.equals(s2) && s2.equals(s3)) && !s1.equals("") && !s2.equals("") && !s3.equals("")) {
            JOptionPane.showMessageDialog(this, "Winner is: " + s1, "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            if (s1.equalsIgnoreCase("X")) {
                xCount++;
            } else {
                oCount++;
            }
            gameScore();
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            startGame = "X";
        }
    }
}
